### ISSUE TITLE
Failed to initialize nvml library

### ISSUE THREAD

**Issue by DWilcott** [nanopool/nanominer#117]
Running RTX 3080 on Windows 10, updated to NVIDIA driver 460.79 and now I get nvml library errors.  Tried uninstall of drivers and clean install, same thing.

2020-12-09 11:12:35: <info> Version 3.1.3-cuda11
2020-12-09 11:12:35: <info>  Started EthMan server on port 3333 without a password (read-only mode).
2020-12-09 11:12:35: <info>  Started web interface on port 9090 without a password.
2020-12-09 11:12:35: <info>  CUDA driver version is 11.2, runtime version is 11.1
2020-12-09 11:12:35: <error>  Failed to initialize nvml library.
2020-12-09 11:12:35: <error>  Failed to init nvml library.
2020-12-09 11:12:36: <info> Detected 0 devices
2020-12-09 11:12:36: <info> Press enter to continue...

**Comment by jimmyhiggs337** [comment]
Also having this issue with a 2080ti, I'm assuming the newest nvidia driver is not supported yet, I've tried the old fix from when this was fin minver of copying nvml.dll from C:\Windows\System32 and then creating the folder C:\Program Files\NVIDIA Corporation\NVSMI and putting nvml.dll into it, but that still didn't work

**Comment by Shedsvartemis** [comment]
I am having the same issue with a 3090. I attempted the same fix as @jimmyhiggs337 but it didn't work.

**Comment by NiTr0oX101** [comment]
Same on my system windows 10 with 1070 the new driver is not compatible with the software.

**Comment by hahnstep** [comment]
Same on my system windows 10 with 2070

**Comment by jimmyhiggs337** [comment]
I have found a temporary solution, remove the new driver and reinstall the previous one

you can use ddu found here: 
https://www.guru3d.com/files-details/display-driver-uninstaller-download.html
to fully remove the new driver

you can find the official download for the previous driver here:
https://www.nvidia.com/Download/Find.aspx

run ddu, choose the remove driver and restart option

once restarted, download the new driver and install (I chose custom install and selected the clean install option just in case) 

then you should be good to go until a fix is released for the newest driver

**Comment by Grumpy-Dwarf** [comment]
Fixed in [nanominer 3.1.4](https://github.com/nanopool/nanominer/releases/tag/v3.1.4) - temperature and power consumption are not reported on latest driver but mining works at least.

**Comment by JarneSt** [comment]
> Fixed in [nanominer 3.1.4](https://github.com/nanopool/nanominer/releases/tag/v3.1.4) - temperature and power consumption are not reported on latest driver but mining works at least.

An older version but it works for now. Not sure how good it is optimisation wise with these newer cards but we'll have to see.
This will do for now

**Comment by BISKITBLOKCHOP** [comment]
Hi GUYS,
Had EXACTLY the same issue. RTX 2080. 
After the latest upgrade : " No GPU detected & unable to run nvml" ,
I was just about to reinstall previous vs BUT GRMPY-DWRF- you Biscuit, the new vs 3.1.4 works like a bomb.

THANK YOU!

**Comment by dirkdiggle** [comment]
> Fixed in [nanominer 3.1.4](https://github.com/nanopool/nanominer/releases/tag/v3.1.4) - temperature and power consumption are not reported on latest driver but mining works at least.

Dang - 3.1.4 is not working with my new 3090 - still getting “Failed to initialize nvml library”.

**Comment by pfsteel** [comment]
I get the same on my rtx 3090

**Comment by pfsteel** [comment]
ok. Got it working for my application by using an older version of cuda

**Comment by JonnyQuest5** [comment]
Getting failed to load  "nvml library" but still mining. does it affect my hashrate or should I just let it run? RTX2080 @ calculated 34Mh/s. New here and not even sure if this is the right place to post this

**Comment by NiTr0oX101** [comment]
> Getting failed to load "nvml library" but still mining. does it affect my hashrate or should I just let it run? RTX2080 @ calculated 34Mh/s. New here and not even sure if this is the right place to post this

no, it should not affect the hashrate

**Comment by JonnyQuest5** [comment]
Ok cool thank you Sent from Mail for Windows 10 From: NiTr0oX101Sent: Saturday, January 9, 2021 3:51 PMTo: nanopool/nanominerCc: JonnyQuest5; CommentSubject: Re: [nanopool/nanominer] Failed to initialize nvml library (#117) Getting failed to load "nvml library" but still mining. does it affect my hashrate or should I just let it run? RTX2080 @ calculated 34Mh/s. New here and not even sure if this is the right place to post thisno, it should not affect the hashrate—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by akissari** [comment]
Hello guys...i buy a rtx 3070 putt it alone for benchmark and its going awesome...when i putt it with the others i have this errors and all is incorrect shares..i take it out and put it in benchmark pc and continued to take this errors with incorrect shares!!! Any help would be great thanks!!!
![IMG_20210128_061139](https://user-images.githubusercontent.com/78130440/106089362-7ee20c00-6130-11eb-8648-511a11b6fb03.jpg)

**Comment by Grumpy-Dwarf** [comment]
> Hello guys...i buy a rtx 3070 putt it alone for benchmark and its going awesome...when i putt it with the others i have this errors and all is incorrect shares..i take it out and put it in benchmark pc and continued to take this errors with incorrect shares!!! Any help would be great thanks!!!
> ![IMG_20210128_061139](https://user-images.githubusercontent.com/78130440/106089362-7ee20c00-6130-11eb-8648-511a11b6fb03.jpg)

Just use latest nanominer -cuda11 version, not the miner on screenshot.

**Comment by akissari** [comment]
again every share is rejected like that!!! with nanominer with oc and stock 
 share denied:provided POW solution is invalid

**Comment by jimmyhiggs337** [comment]
> again every share is rejected like that!!! with nanominer with oc and stock
> share denied:provided POW solution is invalid

Are you sure you’ve entered your crypto wallet information correctly in the config file?  Because it sounds like it’s finding shares but has no place to send them

**Comment by jimmyhiggs337** [comment]
> again every share is rejected like that!!! with nanominer with oc and stock
> share denied:provided POW solution is invalid
I found an issue with this error, and  grumpy dwarf said that it could be an issue caused by over clocking. This is not the same issue that this thread was created for, something else is happening.

**Comment by gunnaraas** [comment]
I have replicated this issue. 

Environment details:
- 1x Nvidia 2060 Super (latest drivers - 461.40)
- nanominer-windows-3.15-cuda11 

Tried DDU & wiping boot drive and the issue remains.

Unlike others, I'm still able to mine without issue, but it'd be nice to have the ability to monitor temps from the terminal.

**Comment by Grumpy-Dwarf** [comment]
NVML library is broken in Nvidia driver, will se for how long. Our job is done by making the workaround. Thanks everybody for help.
Time to close the issue.
