### ISSUE TITLE
Problems of shares rejected nanominer 1.8.0 AMD RX580

### ISSUE THREAD

**Issue by Thorgrlm** [nanopool/nanominer#67]
Hi all, I have test the nanominner 1.8.0 and no work fine, I have many rejected shares, until the work of my miner down, in the versión 1.7.1 my minner work fine.
I have a minner with ubuntu 18.04, three AMD RX580 and one NVIDIA Geforce 1050ti, the GPU's AMD have a custom firmware the speed is at 30MH/s.
someone know what going on?
Thanks

Log:
`2020-02-07 09:30:12: <info>  New job from eth-eu1.nanopool.org:9433
2020-02-07 09:30:12: [Statistics] Ethereum - Total speed: 100.768 MH/s, Total shares: 31 Rejected: 0, Time: 52:58
2020-02-07 09:30:12: [Statistics] Ethereum: GPU 0 12.461 MH/s, GPU 1 29.436 MH/s, GPU 2 29.436 MH/s, GPU 3 29.436 MH/s
2020-02-07 09:30:12: [Statistics] GPU0 t=56°C fan 59%, GPU1 t=58°C fan 43% power 87.02W, GPU2 t=53°C fan 43% power 88.09W, GPU3 t=58°C fan 43% power 87.07W. Total powe$
2020-02-07 09:30:13: <info>  [Ethash] ~~~~~~ DevFee begin ~~~~~~
2020-02-07 09:30:14: <info>  Ethereum: trying to use "stratum" mining protocol... to disable this behaviour, specify: protocol=JSON-RPC
2020-02-07 09:30:15: <info>  Ethereum: trying to use "stratum" mining protocol... to disable this behaviour, specify: protocol=JSON-RPC
2020-02-07 09:30:16: <info>  Ethereum: trying to use "stratum" mining protocol... to disable this behaviour, specify: protocol=JSON-RPC
2020-02-07 09:30:16: <info>  Ethereum: trying to use "stratum" mining protocol... to disable this behaviour, specify: protocol=JSON-RPC
2020-02-07 09:30:17: <info>  Ethereum: trying to use "stratum" mining protocol... to disable this behaviour, specify: protocol=JSON-RPC
2020-02-07 09:30:17: <info>  Ethereum: trying to use "stratum" mining protocol... to disable this behaviour, specify: protocol=JSON-RPC
2020-02-07 09:30:18: <info>  Ethereum: trying to use "stratum" mining protocol... to disable this behaviour, specify: protocol=JSON-RPC
2020-02-07 09:30:18: <info>  Ethereum: trying to use "stratum" mining protocol... to disable this behaviour, specify: protocol=JSON-RPC
2020-02-07 09:30:19: <info>  Ethereum: trying to use "stratum" mining protocol... to disable this behaviour, specify: protocol=JSON-RPC
2020-02-07 09:30:20: <info>  Ethereum: trying to use "stratum" mining protocol... to disable this behaviour, specify: protocol=JSON-RPC
2020-02-07 09:30:20: <info>  Ethereum: trying to use "stratum" mining protocol... to disable this behaviour, specify: protocol=JSON-RPC
2020-02-07 09:30:21: <info>  Ethereum: trying to use "stratum" mining protocol... to disable this behaviour, specify: protocol=JSON-RPC
2020-02-07 09:30:22: <info>  Ethereum: trying to use "stratum" mining protocol... to disable this behaviour, specify: protocol=JSON-RPC
2020-02-07 09:30:22: <info>  Ethereum: trying to use "stratum" mining protocol... to disable this behaviour, specify: protocol=JSON-RPC
2020-02-07 09:30:23: <info>  Ethereum: trying to use "stratum" mining protocol... to disable this behaviour, specify: protocol=JSON-RPC
2020-02-07 09:30:23: <info>  Ethereum: trying to use "stratum" mining protocol... to disable this behaviour, specify: protocol=JSON-RPC
2020-02-07 09:30:24: <info>  Ethereum: trying to use "stratum" mining protocol... to disable this behaviour, specify: protocol=JSON-RPC`

`2020-02-07 09:31:26: <info>  Ethereum: trying to use "stratum" mining protocol... to disable this behaviour, specify: protocol=JSON-RPC
2020-02-07 09:31:26: <info>  [Ethash] ~~~~~~ DevFee end ~~~~~~
2020-02-07 09:31:26: <info>  Connecting to pools...
2020-02-07 09:31:26: <info>  Ethereum: trying to use "stratum" mining protocol... to disable this behaviour, specify: protocol=JSON-RPC
2020-02-07 09:31:27: <info>  New job from eth-eu1.nanopool.org:9433
2020-02-07 09:31:27: [Statistics] Ethereum - Total speed: 100.766 MH/s, Total shares: 31 Rejected: 0, Time: 54:13
2020-02-07 09:31:27: [Statistics] Ethereum: GPU 0 12.461 MH/s, GPU 1 29.433 MH/s, GPU 2 29.435 MH/s, GPU 3 29.437 MH/s
2020-02-07 09:31:27: [Statistics] Ethereum last 10 min - GPU 0: 12.461 MH/s, GPU 1: 29.433 MH/s, GPU 2: 29.435 MH/s, GPU 3: 29.437 MH/s. Total: 100.766 MH/s.
2020-02-07 09:31:58: [Statistics] Ethereum - Total speed: 100.770 MH/s, Total shares: 31 Rejected: 0, Time: 54:44
2020-02-07 09:31:58: [Statistics] Ethereum: GPU 0 12.461 MH/s, GPU 1 29.437 MH/s, GPU 2 29.433 MH/s, GPU 3 29.438 MH/s
2020-02-07 09:31:58: [Statistics] GPU0 t=56°C fan 59%, GPU1 t=58°C fan 43% power 86.21W, GPU2 t=53°C fan 43% power 87.22W, GPU3 t=58°C fan 43% power 87.19W. Total powe$
2020-02-07 09:32:13: <info>  New job from eth-eu1.nanopool.org:9433`

`2020-02-07 09:32:59: <info>  New job from eth-eu1.nanopool.org:9433
2020-02-07 09:32:59: [Statistics] Ethereum - Total speed: 100.767 MH/s, Total shares: 31 Rejected: 0, Time: 55:45
2020-02-07 09:32:59: [Statistics] Ethereum: GPU 0 12.461 MH/s, GPU 1 29.434 MH/s, GPU 2 29.435 MH/s, GPU 3 29.437 MH/s
2020-02-07 09:32:59: [Statistics] GPU0 t=56°C fan 59%, GPU1 t=58°C fan 43% power 87.11W, GPU2 t=52°C fan 43% power 88.09W, GPU3 t=57°C fan 43% power 87.18W. Total powe$
2020-02-07 09:33:28: <info>  Ethereum - SHARE FOUND (GPU: 2, nonce: 0x09a9b212245a8f14).
2020-02-07 09:33:28: <info> Ethereum: share denied: Wrong params (161 ms).
2020-02-07 09:33:30: [Statistics] Ethereum - Total speed: 100.763 MH/s, Total shares: 32 Rejected: 1, Time: 56:16
2020-02-07 09:33:30: [Statistics] Ethereum: GPU 0 12.460 MH/s, GPU 1 29.433 MH/s, GPU 2 29.438 MH/s, GPU 3 29.433 MH/s
2020-02-07 09:33:38: <info>  New job from eth-eu1.nanopool.org:9433`

`2020-02-07 09:36:48: <info>  New job from eth-eu1.nanopool.org:9433
2020-02-07 09:36:48: [Statistics] Ethereum - Total speed: 100.769 MH/s, Total shares: 34 Rejected: 3, Time: 59:33
2020-02-07 09:36:48: [Statistics] Ethereum: GPU 0 12.461 MH/s, GPU 1 29.438 MH/s, GPU 2 29.431 MH/s, GPU 3 29.440 MH/s
2020-02-07 09:36:48: [Statistics] GPU0 t=55°C fan 59%, GPU1 t=58°C fan 43% power 87.02W, GPU2 t=53°C fan 43% power 88.02W, GPU3 t=58°C fan 43% power 87.14W. Total powe$
2020-02-07 09:36:54: <info>  Ethereum - SHARE FOUND (GPU: 1, nonce: 0xab5ef2a8b538ba88).
2020-02-07 09:36:54: <info> Ethereum: share denied: Wrong params (120 ms).
2020-02-07 09:37:04: <info>  New job from eth-eu1.nanopool.org:9433`

**Comment by charliec94** [comment]
I am also having the same issue

**Comment by Grumpy-Dwarf** [comment]
Does this always start after devfee?

**Comment by Thorgrlm** [comment]
I don't know, i saw that version no work and stop it fast, if you want, i can send you  the log file

**Comment by Grumpy-Dwarf** [comment]
Yes, could you please send log to support@nanominer.org ?
There is a `protocol=JSON-RPC` option for Ethash section that can probably workaround this bug.

**Comment by Thorgrlm** [comment]
done , I already sent you the email
thanks

**Comment by Grumpy-Dwarf** [comment]
Please check if just-released [nanominer 1.8.1](https://github.com/nanopool/nanominer/releases/tag/v1.8.1) has this issue fixed.

**Comment by Thorgrlm** [comment]
Hi, I'm test the nanominer 1.8.1 and now I think work fine

[img]https://i.imgur.com/ar0iLXm.png[/img]

**Comment by Grumpy-Dwarf** [comment]
Thanks. If anyone experience this problem with 1.8.1+ versions feel free to reopen the issue or make a new one.

**Comment by DarthMiner88** [comment]
I have the same issue but with an RX570, Memtweak was 1 and change it to 0 and the rate of rejected shares became lower but still happening a lot, 235 shares, bad ones 120 :(, i got 3 cards and just happens in 1
